platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

project '../networking-api/NetworkingApi.xcodeproj'
workspace '../networking-api/NetworkingApi.xcworkspace'

target 'NetworkingApiTests' do
  pod 'SwiftCommons', git: 'git@github.com:roxiemobile/swift-commons.ios.git'
  pod 'NetworkingApi', path: '../../'
end
