source 'https://github.com/roxiemobile/shared-cocoa-frameworks.ios.git'

platform :ios, '8.0'
use_frameworks!

workspace '../RoxieMobile.NetworkingApi/NetworkingApi.xcworkspace'


target 'NetworkingApi.Converters' do
  project '../RoxieMobile.NetworkingApi/Sources/Converters/NetworkingApi.Converters.xcodeproj'

  # Dependencies
  pod 'SwiftCommonsData', git: 'https://github.com/roxiemobile/swift-commons.ios.git', branch: 'feature/refactoring-of-project-structure'
  pod 'SwiftyJSON/Static', '~> 4.0.0'
end


target 'NetworkingApi.Helpers' do
  project '../RoxieMobile.NetworkingApi/Sources/Helpers/NetworkingApi.Helpers.xcodeproj'

  # Dependencies
  pod 'Alamofire/Static', '~> 4.5.1'
  pod 'SwiftCommonsLang',    git: 'https://github.com/roxiemobile/swift-commons.ios.git', branch: 'feature/refactoring-of-project-structure'
  pod 'SwiftCommonsLogging', git: 'https://github.com/roxiemobile/swift-commons.ios.git', branch: 'feature/refactoring-of-project-structure'
end


target 'NetworkingApi.Http' do
  project '../RoxieMobile.NetworkingApi/Sources/Http/NetworkingApi.Http.xcodeproj'

  # Dependencies
  pod 'SwiftCommonsConcurrent',   git: 'https://github.com/roxiemobile/swift-commons.ios.git', branch: 'feature/refactoring-of-project-structure'
  pod 'SwiftCommonsDiagnostics',  git: 'https://github.com/roxiemobile/swift-commons.ios.git', branch: 'feature/refactoring-of-project-structure'
  pod 'SwiftCommonsLang',         git: 'https://github.com/roxiemobile/swift-commons.ios.git', branch: 'feature/refactoring-of-project-structure'

  # DELETE:
  pod 'SwiftCommonsAbstractions', git: 'https://github.com/roxiemobile/swift-commons.ios.git', branch: 'feature/refactoring-of-project-structure'
  pod 'SwiftCommonsExtensions',   git: 'https://github.com/roxiemobile/swift-commons.ios.git', branch: 'feature/refactoring-of-project-structure'
  pod 'SwiftCommonsLogging',      git: 'https://github.com/roxiemobile/swift-commons.ios.git', branch: 'feature/refactoring-of-project-structure'
  pod 'SwiftCommonsObjC',         git: 'https://github.com/roxiemobile/swift-commons.ios.git', branch: 'feature/refactoring-of-project-structure'
end


target 'NetworkingApi.Rest' do
  project '../RoxieMobile.NetworkingApi/Sources/Rest/NetworkingApi.Rest.xcodeproj'

  # Dependencies
  pod 'Alamofire/Static', '~> 4.5.1'
  pod 'SwiftCommonsData', git: 'https://github.com/roxiemobile/swift-commons.ios.git', branch: 'feature/refactoring-of-project-structure'
  pod 'SwiftyJSON/Static', '~> 4.0.0'
end
