source 'https://github.com/roxiemobile/shared-cocoa-frameworks.ios.git'

platform :ios, '8.0'
use_frameworks!

workspace '../RoxieMobile.NetworkingApi/NetworkingApi.xcworkspace'


target 'NetworkingApi.Core.Converters' do
  project '../RoxieMobile.NetworkingApi/Core.Converters/NetworkingApi.Core.Converters.xcodeproj'

  pod 'NetworkingApi/Core/Net', path: '../../'

  target 'NetworkingApi.Core.Converters.UnitTests' do
    inherit! :search_paths
  end
end


target 'NetworkingApi.Core.Net' do
  project '../RoxieMobile.NetworkingApi/Core.Net/NetworkingApi.Core.Net.xcodeproj'

  pod 'Alamofire', '~> 4.5.1'
# pod 'Dispatch', '~> 2.0.3'
  pod 'SwiftCommons/Core/Concurrent', :git => 'https://github.com/roxiemobile/swift-commons.ios.git', :branch => 'sandbox'
  pod 'SwiftCommons/Core/Data', :git => 'https://github.com/roxiemobile/swift-commons.ios.git', :branch => 'sandbox'
  pod 'SwiftyJSON', '~> 3.1.4'

  target 'NetworkingApi.Core.Net.UnitTests' do
    inherit! :search_paths
  end
end
