source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'
use_frameworks! :linkage => :static

workspace '../RoxieMobile.NetworkingApi/NetworkingApi.xcworkspace'


# MARK: - Methods

def inject_shared_dependencies_1
  pod 'SwiftCommons/Data', '~> 1.6.0'
  pod 'SwiftyJSON', '~> 5.0.1'
end

def inject_shared_dependencies_2
  pod 'Alamofire', '~> 4.9.1'
end


# MARK: - Sources

target 'NetworkingApi.Helpers' do
  project '../RoxieMobile.NetworkingApi/Sources/Helpers/NetworkingApi.Helpers.xcodeproj'

  # Dependencies
  inject_shared_dependencies_2
  pod 'SwiftCommons/Logging', '~> 1.6.0'
end

target 'NetworkingApi.Http' do
  project '../RoxieMobile.NetworkingApi/Sources/Http/NetworkingApi.Http.xcodeproj'

  # Dependencies
  pod 'SwiftCommons/Diagnostics', '~> 1.6.0'
end

target 'NetworkingApi.ObjC' do
  project '../RoxieMobile.NetworkingApi/Sources/ObjC/NetworkingApi.ObjC.xcodeproj'

  # Dependencies
  inject_shared_dependencies_2
end

target 'NetworkingApi.Rest' do
  project '../RoxieMobile.NetworkingApi/Sources/Rest/NetworkingApi.Rest.xcodeproj'

  # Dependencies
  inject_shared_dependencies_1
  inject_shared_dependencies_2
end
